### ISSUE TITLE
Potential calculation error in the code

### ISSUE THREAD

**Issue by YOxidized** [GenericMadScientist/AI-Team-Manipulator#1]
Hello!  First, I want to say that this tool is extremely accurate, I have found very few results in my routing of this game that conflict with your tool.  However, deep into R2, i was finally able to find a situation that is a contradiction.  It occurred during this fight:

![image](https://user-images.githubusercontent.com/79140667/211125726-6222cef8-99c6-4629-8bad-33e07af68908.png)

![image](https://user-images.githubusercontent.com/79140667/211125747-b755e74b-031d-4cc2-8d6f-f765258c4403.png)

However, she regularly present a team of Snorlax/Tyranitar/Kingdra, which is not even on the list.  

When I switch Graveler in the tool to another ground type, I get a list of teams that I have been seeing in my actual game.

![image](https://user-images.githubusercontent.com/79140667/211125856-3448af23-5465-402e-b332-a82758c37d25.png)

![image](https://user-images.githubusercontent.com/79140667/211125865-5d6a3dc5-b2c5-4536-aa72-6dc9eb9ab51d.png)

There may be something happening with rock types, or a small calculation error occurring somewhere, but I wanted to bring this to your attention because I have been using the tool a ton lately with great success.  Thank you again for providing it to us!

**Comment by GenericMadScientist** [comment]
The problem is that the game thinks Wobbuffet can't learn any moves, which messes up the calculation for how much damage Wobbuffet can do back. This is not a big difference since Counter and Mirror Coat are just treated as base power 1 moves, but in this case it's just enough to matter. I anticipated this bug at the end of [step 1](https://genericmadscientist.github.io/posts/ps2-ai-teams/#step-1-damage-you-can-do) of the damage calculation part of my blog post, but forgot Counter and Mirror Coat count as doing a small amount of damage. This occurs regardless of whether I put Wobbuffet as first or second in the team, so my speculation about it only mattering for the first poké seems to have been incorrect.

I'm going to go through the above examples and remove the affected moves as ones the AI thinks they can learn, so let me know if you see this breaking anything. When I do it for Wobbuffet, this is the result which checks with what I get with testing in-game.
![results](https://user-images.githubusercontent.com/22206651/211171376-043f4e71-4d02-4851-838d-be02fa9c307e.png)

**Comment by YOxidized** [comment]
This is really insightful, and through my empirical testing makes perfect sense.  Throughout my entire time playing through the game, I found only one example of potential inaccuracy in team selection, and that was vs Gym Leader Blue in R2, another fight where I chose to bring Wobbuffet.  However, in that case, the teams themselves were the same, but I felt that the team distribution was off, so I had no real proof that it was anything other than RNG at work.  

Once again, thank you very much for providing this tool, and thank you also for responding to this!

EDIT:  Also, that table you provided looks accurate for the results I saw in game.
